### ISSUE TITLE
Problems updating mysql database

### ISSUE THREAD

**Issue by eldanet** [paypal/ipn-code-samples#98] opened 2017-07-13 17:43 UTC
### General information

* Environment: Sandbox
* Language: PHP 5.6 on Apache

### Issue description

As a developer, I used your script to check PayPal payment transaction successfully.
Problems came when I wanted to update database with the transaction id.

As a model I used the advanced example and put my code after the // Process IPN line.
First I send a confirmation email to the user (and it works), then to the seller (and it works).

Then I tried to update database using a Class that I use all over the site, but it doesn't work, silently failing. Script fails even only constructing the new class to recall useful variables (host, user, password and db_name).

Following the advice of a user, I tried connecting with PDO but script silently fails (even ignoring try - catch blocks) and Ipn calls repeat until I comment the PDO block of script.
I tested the PDO script in a page apart and it works perfectly.

Finally I managed updating my database with mysqli, but also in this case it worked only using Procedural style (mysqli_connect); Object oriented style (new mysqli) silently fails.
Also the class that I tried to use is object oriented styled, maybe it fails for the same reason.

I think you should advice the users of your script about this limits.

Best regards.

**Comment by pp-randy** [comment] 2017-07-14 14:56
The PHP script is highly community developed, if you would like to submit a pull request to add additional features then I would be happy to review it.

**Comment by overint** [comment] 2017-07-14 15:04
I don't see how this would have anything to do with our PHP example. It sounds like your server is misconfigured, as our class does not interact with anything except curl.

**Comment by overint** [comment] 2017-07-22 00:04
I'll give you another few days to provide an update, otherwise I will close this as it does not seem related to our code.

**Comment by eldanet** [comment] 2017-07-24 16:11
Sorry for late answer, but I really can't figure out how my class could interact with your script, since yours has nothig to do with mysql.
I can only show you my script so that you can understand better what happens.

The class I use to interface with mysql is this one:

```
class MysqlClass {
 	private $host = "localhost";
	private $db = "db_name";
	private $user = "my_username";
	private $password = "my_password";
	
	public $conn;
	private $attiva = false;

	public function connetti() {
		if (!$this->attiva) {
			$this->conn = new mysqli($this->host,$this->user,$this->password,$this->db);
			if ($this->conn->connect_error) {
				trigger_error("Database connection failed: "  . $this->conn->connect_error, E_USER_ERROR);
			}
		} else {
			return true;
		}
	}

	public function query($sql) {
		if(isset($this->attiva)) {
			//echo $sql;
			$rs = $this->conn->query($sql);
			if($rs === false) {
				trigger_error("Wrong SQL: $sql <br>Error: " . $this->conn->error, E_USER_ERROR);
			} else {
				return $rs; 
			}
		} else {
			return false; 
		}
	}
 
	public function estrai($risultato) {
		if(isset($this->attiva)) {
			$r = $risultato->fetch_object();
			return $r;
		} else {
			return false; 
		}
	}
	
	public function aggiorna($t,$val,$campi = null) {
		
// ...... my update string
			
	}

	public function disconnetti() {
		if($this->attiva) {
			if(mysqli_close()) {
				$this->attiva = false; 
				return true; 
			} else {
				return false; 
			}
		}
	}
	
}
```

The script I use in my IPN:

```
namespace Listener;

// Set this to true to use the sandbox endpoint during testing:
$enable_sandbox = true;

// Use this to specify all of the email addresses that you have attached to paypal:
$my_email_addresses = array(my_email, my_sandbox_email);

// Set this to true to send a confirmation email:
$send_confirmation_email = true;
$confirmation_email_address = "XYZ <my_email>";
if ($enable_sandbox) $confirmation_email_address = "XYZ <my_sandbox_email>";
$from_email_address = "XYZ <my_email>";

// Set this to true to save a log file:
$save_log_file = true;
$log_file_dir = __DIR__ . "/logs";

require('PaypalIPN.php');
use PaypalIPN;
$ipn = new PaypalIPN();
if ($enable_sandbox) {
    $ipn->useSandbox();
}
$verified = $ipn->verifyIPN();

$data_text = "";
foreach ($_POST as $key => $value) {
    $data_text .= $key . " = " . $value . "\r\n";
}

$test_text = "";
if ($_POST["test_ipn"] == 1) {
    $test_text = "Test ";
}

// Check the receiver email to see if it matches your list of paypal email addresses
$receiver_email_found = false;
foreach ($my_email_addresses as $a) {
    if (strtolower($_POST["receiver_email"]) == strtolower($a)) {
        $receiver_email_found = true;
        break;
    }
}

date_default_timezone_set("Europe/Rome");
list($year, $month, $day, $hour, $minute, $second, $timezone) = explode(":", date("Y:m:d:H:i:s:T"));
$date = $year . "-" . $month . "-" . $day . "_" . $hour . "-" . $minute;
$timestamp = $date . " " . $hour . ":" . $minute . ":" . $second . " " . $timezone;
$dated_log_file_dir = $log_file_dir . "/" . $year . "/" . $month;


$paypal_ipn_status = "VERIFICATION FAILED";
if ($verified) {
    $paypal_ipn_status = "RECEIVER EMAIL MISMATCH";
    if ($receiver_email_found) {
			$paypal_ipn_status = "Completed Successfully";
		// IT WORKS			

			// Process IPN
			$id_transazione = $_POST['txn_id'];
			$auth_amount = $_POST['mc_gross'];
			$id_ordine = trim($_POST['custom']);
			$payer_email = $_POST['payer_email'];
			$email_to = $_POST["first_name"] . " " . $_POST["last_name"] . " <" . $payer_email . ">";
			if ($enable_sandbox) $email_to = "XYZ <my_sandbox_email>";
			$email_subject = "Conferma pagamento ordine #". $id_ordine;

		// send confirmation email to customer			
			mail($email_to, $email_subject, $email_body, "From: " . $from_email_address);
		// IT WORKS			

		// send confirmation email to vendor IT WORKS	
			$sent = mail($confirmation_email_address, $email_subject, $email_body, "From: " . $from_email_address);
		// IT WORKS			

			// database update
			require('funzioni_mysql.php');

			$data = new MysqlClass();
			// STOPS WORKING HERE!

    }

} elseif ($enable_sandbox) {
    if ($_POST["test_ipn"] != 1) {
        $paypal_ipn_status = "RECEIVED FROM LIVE WHILE SANDBOXED";
    }
} elseif ($_POST["test_ipn"] == 1) {
    $paypal_ipn_status = "RECEIVED FROM SANDBOX WHILE LIVE";
}

if ($save_log_file) {
    // Create log file directory
    if (!is_dir($dated_log_file_dir)) {
        if (!file_exists($dated_log_file_dir)) {
            mkdir($dated_log_file_dir, 0777, true);
            if (!is_dir($dated_log_file_dir)) {
                $save_log_file = false;
            }
        } else {
            $save_log_file = false;
        }
    }
    // Restrict web access to files in the log file directory
    $htaccess_body = "RewriteEngine On" . "\r\n" . "RewriteRule .* - [L,R=404]";
    if ($save_log_file && (!is_file($log_file_dir . "/.htaccess") || file_get_contents($log_file_dir . "/.htaccess") !== $htaccess_body)) {
        if (!is_dir($log_file_dir . "/.htaccess")) {
            file_put_contents($log_file_dir . "/.htaccess", $htaccess_body);
            if (!is_file($log_file_dir . "/.htaccess") || file_get_contents($log_file_dir . "/.htaccess") !== $htaccess_body) {
                $save_log_file = false;
            }
        } else {
            $save_log_file = false;
        }
    }

	// Save data to text file
	file_put_contents($dated_log_file_dir . "/" . $test_text . "paypal_ipn_" . $date . ".txt", "paypal_ipn_status = " . $paypal_ipn_status . "\r\n" . "paypal_ipn_date = " . $timestamp . "\r\n" . $data_text . "\r\n", FILE_APPEND);
}

if ($send_confirmation_email) {
    // Send confirmation email
    mail($confirmation_email_address, $test_text . "PayPal IPN : " . $paypal_ipn_status, "paypal_ipn_status = " . $paypal_ipn_status . "\r\n" . "paypal_ipn_date = " . $timestamp . "\r\n" . $data_text, "From: " . $from_email_address);
}

// Reply with an empty 200 response to indicate to paypal the IPN was received correctly
header("HTTP/1.1 200 OK");

```

As I told You, I managed to make the script working, making a full myslqi connection and update, but I would like to understand why my class doesn't work here.

Neigher it works a PDO connection that I tried:

```
try {
	$conn = new PDO("mysql:host=localhost;dbname=my_db_name",my_username,my_password);
	$str_update = "UPDATE ". $tbl_prefix ."_pagamenti SET id_transazione = :id_transazione, id_stato = :id_stato WHERE id = :id";
	$q = $conn->prepare($str_update);
	$count = $q->execute(array(':id_transazione'=>$id_transazione, ':id_stato' => 2, ':id'=>$id_ordine
	if ($count === false) {
		$data_text .= "Database PDO update failed: ". print_r($q->errorInfo()) . "<br>");
	}
} catch (PDOException $e) {
	$data_text .= "Database MySqli connection failed: ". $e->getMessage() . "<br>");
}
```
Thanks in advance.

**Comment by pp-randy** [comment] 2017-07-26 15:30
I think the execute should look like:
`$q->execute(array('id_transazione'=>$id_transazione, 'id_stato' => 2, 'id'=>$id_ordine))` I believe you need to drop the `:` on your names in the actual execute, but keep them in the prepare function. 

What is the error that is returned?  You are updating a record instead of inserting a new one? 

Also this third party tutorial might be helpful https://phpdelusions.net/pdo#prepared

**Comment by eldanet** [comment] 2017-07-28 11:42
I'm not interested in PDO connection. It was just a test following a user in a forum that suggested to use PDO connection instead of mysqli. Nevertheless, the execute is ok. I tested it in a file apart and it works perfectly.
What I'm interested in is to use my class and its variables and functions (db, user, pass, input filed sanitization) to update a record already inserted.
The problem is that the script silently fails as I call the new class. $data = new MysqlClass();
I tried to put try - catch to get the error but, as for the PDO connection, it simply fails returning no error.
The script stops and never reach the end.
You can test it inserting your connection strings in the class I posted and simply calling it.

**Comment by pp-randy** [comment] 2017-07-28 14:56
I think it might be best if you extract the SQL query your function is building and I can look it over.  

I see examples here for helping to catch mysqli errors https://stackoverflow.com/questions/17053466/how-to-display-errors-for-my-mysqli-query

**Comment by eldanet** [comment] 2017-07-28 15:12
Maybe I was not clear.
This is my Class:

```
class MysqlClass {
 	private $host = "localhost";
	private $db = "db_name";
	private $user = "my_username";
	private $password = "my_password";
	
	public $conn;
	private $attiva = false;

	public function connetti() {
		if (!$this->attiva) {
			$this->conn = new mysqli($this->host,$this->user,$this->password,$this->db);
			if ($this->conn->connect_error) {
				trigger_error("Database connection failed: "  . $this->conn->connect_error, E_USER_ERROR);
			}
		} else {
			return true;
		}
	}

	public function query($sql) {
		if(isset($this->attiva)) {
			//echo $sql;
			$rs = $this->conn->query($sql);
			if($rs === false) {
				trigger_error("Wrong SQL: $sql <br>Error: " . $this->conn->error, E_USER_ERROR);
			} else {
				return $rs; 
			}
		} else {
			return false; 
		}
	}
 
	public function estrai($risultato) {
		if(isset($this->attiva)) {
			$r = $risultato->fetch_object();
			return $r;
		} else {
			return false; 
		}
	}
	
	public function aggiorna($t,$val,$campi = null) {
		
// ...... my update string
			
	}

	public function disconnetti() {
		if($this->attiva) {
			if(mysqli_close()) {
				$this->attiva = false; 
				return true; 
			} else {
				return false; 
			}
		}
	}
	
}
```

And this is the interested part of your script:

```
if ($verified) {
    $paypal_ipn_status = "RECEIVER EMAIL MISMATCH";
    if ($receiver_email_found) {

        // other stuff....

	// database update
       require('funzioni_mysql.php'); // my class
       $data = new MysqlClass();

       // STOPS WORKING HERE!
    }

} elseif ($enable_sandbox) {
    if ($_POST["test_ipn"] != 1) {
        $paypal_ipn_status = "RECEIVED FROM LIVE WHILE SANDBOXED";
    }
} elseif ($_POST["test_ipn"] == 1) {
    $paypal_ipn_status = "RECEIVED FROM SANDBOX WHILE LIVE";
}
```
No call to Class functions at all, no query.
I made a test simply calling $data->host; but I cannot retrieve the value and no error is returned

**Comment by pp-randy** [comment] 2017-07-28 15:17
Unfortunately. I'm not sure what is wrong with your class.  Seems just including it is causing the failure. 

When you did try catch, what was the error?

https://stackoverflow.com/questions/12642230/in-php-what-happens-when-an-object-fails-to-be-instantiated

**Comment by eldanet** [comment] 2017-07-28 16:05
No error returned...
Just stopped.
My Class is ok. It's years that I use it everywhere without problems! Just changed from mysql to mysqli.

Could it be a problem with namespaces?

**Comment by overint** [comment] 2017-07-28 21:48
As much as we would like to help, this has nothing to do with our sample.
I would suggest you step through your code line by line using Xdebug and figure out where the problem is.
The class is not namespaced.

**Closed** 2017-08-10 14:41 UTC
Labels: invalid

**Comment by evilcoder04** [comment] 2018-05-13 02:11
@eldanet Hi found a solution, but you need to use PDO connection (as you said you don't prefer it).
I added this at the beginning of the PaypalIPN 
`
    private $host = "localhost";
    private $db_name = "dbtest";
    private $username = "root";
    private $password = "";
    public $conn;
     
    public function dbConnection() {
        $this->conn = null;    
        try {
            $this->conn = new PDO("mysql:host=" . $this->host . ";dbname=" . $this->db_name, $this->username, $this->password);
            $this->conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);   
        }
        catch(PDOException $exception) {
            echo "Connection error: " . $exception->getMessage();
        }         
        return $this->conn;
    }
    `
   And I use it like this: (note I am fetching a date from the tbl_users' userEnd column)
`
$get_date = $db->prepare("SELECT userEnd FROM tbl_users WHERE userID = :user_id");
$get_date->execute(array(":user_id" => $user_id));
$date = $get_date->fetch();

$got_date = $date[0];
`

Before when I am fetching the prepared statement like this: (preferably to only fetch with named indexes not with numbered indexes)
`
$date = $get_date->fetch(PDO::FETCH_ASSOC);
`
That was on line 28 of my code. I always get this error:

<b>Fatal error</b>:  Uncaught Error: Class 'Listener\PDO' not found in C:\xampp\htdocs\paypal-ipn\secret-notify-url-for-paypal-ipn.php:28
Stack trace:
#0 {main}
  thrown in <b>C:\xampp\htdocs\paypal-ipn\secret-notify-url-for-paypal-ipn.php</b> on line <b>28</b><br />

Note: I also don't know why that doesn't work and how my solution works. I just tried it out.
