### ISSUE TITLE
Getting INVALID IPN status every time

### ISSUE THREAD

**Issue by digiogi** [paypal/ipn-code-samples#24] opened 2014-10-15 19:23 UTC
I'm getting INVALID IPN status every time even the payment is made.

I'm using the php api.

Is there any way to do this properly?

**Comment by urgido** [comment] 2015-12-30 07:14
Replace the existing with
if (strpos($res, "VERIFIED") !== 0){

**Comment by pp-randy** [comment] 2016-09-19 16:21
Closing as a duplicate of https://github.com/paypal/ipn-code-samples/issues/51

**Closed by pp-randy** 2016-09-19 16:21 UTC
Labels: duplicate
